using Pkg;

Pkg.add("Calculus");
Pkg.add("Cubature");
Pkg.add("Distributions");
Pkg.add("XLSX");
Pkg.add("ForwardDiff");
Pkg.add("GLPK");
Pkg.add("Interpolations");
Pkg.add("Ipopt");
Pkg.add("JLD");
Pkg.add("JuMP");
Pkg.add("LaTeXStrings");
Pkg.add("NLsolve");
Pkg.add("Optim");
Pkg.add("Plots");
Pkg.add("PyPlot");
Pkg.add("QuadGK");
Pkg.add("QuantEcon");
Pkg.add("Roots");
